dist: trusty
language: node_js
node_js:
  - "8"
services:
  - docker
addons:
  sonarcloud:
    organization: "tourlive"
    token:
      secure: "VIYzcxAZpzDnY4r7sKoLfNWDB51chJjSmfqq1wXMZgPiipy67KOQJPdTBaZON45GhOJFIBsfT4/JEqYKzayEb4uLw8KfXIgMEAZJgl+5BXQSC9FgcivQ75met0ey/si+5kjKefgGbC/aKoLfIoFrLE0Re/tBlCZbRCmvp6fafDG1XVVKbF6UpVqBcWDG20Mkjc7UHEauEpteCtTaAHcGl/cHiS8YBFHAb9CqIGKlhPXxsqNPVtgInpn5FFkS/jBzGuNkmqPWWiOBEN5NAkhSC5rtJL4Lb7NA3tWkkK8/RqUeu48Jl/NmO/3QgicZOMVHF8RDwg3bjIhQ+l+nAJC/pxGx0pdsYrVohtPqWDErNeKg1d4YElJEHrT+jIZmjjeXZxpH/spr/NZHk1agW+rdCuDPrxJv4AiQlKELZq4TDqkQOx2GZsMn32NZvzg5RohPTTEOjrcKfZzwMDTymKaSEHIjMhO7JpPY/8ZuHRxQJUUUYkk7mJz4mVhvTo/pskb17ubaoot/7qrQ83B1unZBwSDi33u8M6bSuB7cZ8Z5ZFmXZ6mUz4sjZ3vHx1lpiSQoWh5RUsXeHlx0kWURT+tN1ONsSHOFDxaasOgTtU6U81LJ8z8P56SdhEEO4vuRWvRENr9pT7k3nutUTj0O/NEecTsf79O1bZO8iY8NdWPzzX0="
    github_token:
      secure: "swe7kwOKxGOdaYXOqlvsycYYGbQKatfNbP4XPSZ5oawmr4z3flpvXt78cOUCME8MuVVpqhpIsMX71r5uZcHBIeF+ZFEZgoRp+aWj3SXoU+odSGc1NNDwJQIzlzxrZhmskCdybbQYemXJCHV4JBmi+KwqEyZLotIYHM97FQK71WgEhtnABc6w4o6ttT35j2hib9l2916lF3skHaCHJwPxP4tYdPc9UkLHG+Kuqyn7PwACSIwN98mCbjL3vYZDXQ+7AM3BFOfiau/322Vup9Ssw3QWI1LV3UVPnfqmT+mkm36R8ZgpI6sKKHuqAQDnv4lam0phcZTW4zei+q6TRCK89l1nQYniuZofAq5RBo9vWUFOZ4jtqVeDaBbT8xn0MzM2oCV+TIwtrhqLp4qLcH/LNj2Km0NgkRxOcqptROAKq6NQvF5ELmPs8T0p1lAzOei3SblnNeJFtdwI7z2VxZbzpJmajDzzBIq+JJNdZ/55Ri8iBrRGq3JgxCzGf/GRITGNuNYFcs2TPvMLs/AUmjkVdC04woaONNamEB0Khsf/IyfOEIMS4H8GRtuaUZosfbfEGA2rEyeruTbk4iEl5Gl45E3vn5tbccyf/nznmCSN7ksm5JEnHwUz8vyZnEKIT0BGYNR3nRtV/b8XUJ2XsMbz3/KaMaKFPu6FK19ql2VogCk="
cache:
  yarn: true
  directories:
    - '$HOME/.sonar/cache'
deploy:
  - provider: script
    script: bash docker_push_prod
    on:
      branch: master
  - provider: script
    script: bash docker_push_dev
    on:
      branch: dev
branches:
  only:
  - master
  - dev
script:
  - yarn test --coverage
  - sonar-scanner
