#!/bin/bash
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
prop="version"
actual_version="$(node -pe "require('./package.json')['$prop']")"
echo $actual_version
docker build -t tourlive/frontend:$actual_version .
docker push tourlive/frontend:$actual_version

if [ "$TRAVIS_BRANCH" = "dev"]; then
 docker tag tourlive/frontend:$actual_version tourlive/frontend:latest
 docker push tourlive/frontend:latest
 ssh -p 40001 ufo@sinv-56034.edu.hsr.ch "sh /opt/tourlive/restart-dev.sh" 
fi

if [ "$TRAVIS_BRANCH" = "master"]; then
 docker tag tourlive/frontend:$actual_version tourlive/frontend:stable
 docker push tourlive/frontend:stable
 ssh -p 40001 ufo@sinv-56034.edu.hsr.ch "sh /opt/tourlive/restart-dev.sh"
fi
