export const GET_SETTINGS = "GET_SETTINGS";
export const GET_ACTIVESTAGE ='GET_ACTIVESTAGE';
export const GET_ACTIVERACE ='GET_ACTIVERACE';
export const GET_RIDERS = 'GET_RIDERS';
export const GET_RIDERSTAGECONNECTIONS = 'GET_RIDERSTAGECONNECTIONS';
export const GET_MAILLOTS = 'GET_MAILLOTS';
export const GET_ERROR_MAILLOTS = 'GET_ERROR_MAILLOTS';